<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Outliers">

<title>Regression Models Competition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Models Competition</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Outliers </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">1</span> Executive Summary</h2>
<p>This report outlines the development of a predictive model for residential home prices in Ames, Iowa. The objective was to minimize the Root Mean Squared Error (RMSE) between the predicted logarithm of the sale price and the actual values.</p>
<p>Our analysis proceeded through data cleaning, feature engineering, and the implementation of regularized linear regression models (Ridge, Lasso, and ElasticNet). The final selected approach is an ensemble of these three models, which provides robust predictions by balancing bias and variance. Key drivers of price were identified as the total square footage, overall quality, and neighborhood location.</p>
</section>
<section id="introduction-objectives" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="introduction-objectives"><span class="header-section-number">2</span> Introduction &amp; Objectives</h2>
<p>The goal of this project is to predict the final sale price of homes based on 79 explanatory variables describing (almost) every aspect of residential homes. Anything studied during the course could be used to create the models, but more advanced techniques were out of the scope.</p>
<p>The specific objectives were:</p>
<ol type="1">
<li>Perform Exploratory Data Analysis (EDA) to understand variable distributions and relationships.</li>
<li>Clean the data by handling missing values and outliers.</li>
<li>Engineer new features to capture latent information.</li>
<li>Train and validate predictive models using cross-validation.</li>
<li>Identify the characteristics of the most and least expensive houses.</li>
</ol>
</section>
<section id="exploratory-data-analysis-eda" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="exploratory-data-analysis-eda"><span class="header-section-number">3</span> Exploratory Data Analysis (EDA)</h2>
<section id="preliminary-steps" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="preliminary-steps"><span class="header-section-number">3.1</span> Preliminary steps</h3>
<p>Right away from reading the data, we imputed the missing categories as the feature being missing. In <a href="#sec-imputation-strategy" class="quarto-xref">Section&nbsp;4.2</a> we deglose the process in more detail, but it was important to mention this beforehand.</p>
<p>In the same spirit, since we were clear that many of the available variables were correlated and redundant, we created a handful of interest variables from the beginning to include them in the EDA (refer to <a href="#sec-feature-engineer" class="quarto-xref">Section&nbsp;4.3</a> for a detailed explanation them).</p>
</section>
<section id="analysis-of-the-target-variable-saleprice" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="analysis-of-the-target-variable-saleprice"><span class="header-section-number">3.2</span> Analysis of the Target Variable (<code>SalePrice</code>)</h3>
<p>We began by analyzing the distribution of the dependent variable, <code>SalePrice</code>. The initial histogram (see <a href="#fig-sale-price" class="quarto-xref">Figure&nbsp;1</a>) revealed a significant right skew, indicating that while most homes are moderately priced, there are a few very expensive properties that stretch the distribution.</p>
<div id="fig-sale-price" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sale-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/LogSalePrice-p1.svg" class="img-fluid figure-img"></p>
<figcaption>Histogram of SalePrice</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/LogSalePrice-p2.svg" class="img-fluid figure-img"></p>
<figcaption>Q-Q plot of SalePrice</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/LogSalePrice-p3.svg" class="img-fluid figure-img"></p>
<figcaption>Histogram of log(SalePrice)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/LogSalePrice-p4.svg" class="img-fluid figure-img"></p>
<figcaption>Q-Q plot of log(SalePrice)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sale-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution analysis on the response variable. Original is left-skewed, whereas the log-transformed resembles a normal distribution.
</figcaption>
</figure>
</div>
<p>To address this non-normality and satisfy the assumptions of linear regression, we applied a logarithmic transformation (<code>log(SalePrice)</code>). This resulted in a distribution that much closely approximates a normal curve, as confirmed by the Q-Q plots generated during analysis (again, see <a href="#fig-sale-price" class="quarto-xref">Figure&nbsp;1</a>).</p>
</section>
<section id="correlation-analysis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="correlation-analysis"><span class="header-section-number">3.3</span> Correlation Analysis</h3>
<p>We examined the correlation between numerical predictors and the sale price. The variables with the highest positive correlation were <code>TotalSF</code> (aggregation of the existing area-related variables), <code>TotalBath</code> (weighted-aggregation of the bathrooms and half bathrooms of the house), and <code>GarageCars</code> (size of the garage measured in cars). As an important mark, we used Spearman’s rank correlation coefficient, since it is not affected by monotonic transformations such as the logarithm. See <a href="#fig-top-correlation" class="quarto-xref">Figure&nbsp;2</a> for more details.</p>
<div id="fig-top-correlation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-top-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/top-correlation.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-top-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The ten highest correlated variables with the <code>SalePrice</code> using Spearman’s rank correlation coefficient.
</figcaption>
</figure>
</div>
<p>We also investigated categorical variables. Boxplots of <code>SalePrice</code> against <code>Neighborhood</code> showed significant variation in median prices, confirming that location is a critical determinant of value. Similarly, <code>OverallQual</code> showed a clear monotonic relationship with price. Interestingly, during our analysis, we also saw that <code>ExterQual</code> and <code>KitchenQual</code> are strongly related to an increment in price. See <a href="#fig-categorical" class="quarto-xref">Figure&nbsp;3</a> for more details.</p>
<div id="fig-categorical" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-categorical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/corr_cat.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-categorical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Boxplots of several categorical variables against the sale price. Overall quality, neighborhood, exterior-material quality and kitchen quality are all related to an increase in price, each of them in different levels.
</figcaption>
</figure>
</div>
</section>
<section id="missing-values-analysis" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="missing-values-analysis"><span class="header-section-number">3.4</span> Missing Values Analysis</h3>
<p>A detailed analysis of missing data revealed two distinct types of missingness:</p>
<ol type="1">
<li><strong>Structural Missingness:</strong> Variables like <code>Alley</code>, <code>PoolQC</code>, and <code>Fence</code> had high rates of missing values. However, the data dictionary implies that <code>NA</code> here effectively means “Feature Not Present” (e.g., No Alley access) rather than missing data. Therefore, these values were correctly imputed when reading the data.</li>
<li><strong>Random Missingness:</strong> Variables like <code>LotFrontage</code> showed missingness patterns that required statistical imputation, since the median of the observations without value is higher than those with it (see <a href="#fig-missing-impact" class="quarto-xref">Figure&nbsp;4</a>). The other variables with missing values were <code>Electrical</code>, <code>MasVnrArea</code> and <code>MasVnrType</code>. These last two were an interesting case, since both were missing (and present) at the same time in each row, suggesting both measurements can be taken (or not) at the same time.</li>
</ol>
<div id="fig-missing-impact" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-missing-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/missing_lotfrontage_impact.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-missing-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Boxplot of the distribution of prices (in <span class="math inline">\(log\)</span> scale) grouped by the values of <code>LotFrontage</code> being missing or not. There is a non-trivial difference between both groups.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="data-preprocessing-feature-engineering" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="data-preprocessing-feature-engineering"><span class="header-section-number">4</span> Data Preprocessing &amp; Feature Engineering</h2>
<section id="sec-outliers" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="sec-outliers"><span class="header-section-number">4.1</span> Outlier Detection and Influence Analysis</h3>
<p>Before proceeding with imputation, we performed a diagnostic check to identify observations that could disproportionately bias our model’s parameters. We focused on influential points, which are observations that possess both high leverage and high residuals.</p>
<p>Using a preliminary linear model, we calculated Cook’s Distance for every observation in the training set. We applied the standard threshold of <span class="math inline">\(D_i &gt; 4/(n - k - 1)\)</span> to flag potential problems.</p>
<div id="fig-influence-diag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-influence-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/influential.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-influence-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Diagnostic plots for identifying influential points. The left panel shows Standardized Residuals vs.&nbsp;Leverage with a Cook’s Distance threshold of <span class="math inline">\(D_i &gt; 4/(n-k-1)\)</span>. The right panel demonstrates how removing IDs 1299 and 524 (dashed green line) improves the regression trend for the rest of the market.
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-influence-diag" class="quarto-xref">Figure&nbsp;5</a>, two specific observations (IDs 1299 and 524) were identified as extreme outliers. These properties feature total square footage exceeding 4,000 sq ft but sold for prices significantly below the expected trend for their size. Including these points would “pull” the regression line downward, leading to an underestimation of value for other large properties. Consequently, these two observations were removed to ensure model robustness.</p>
</section>
<section id="sec-imputation-strategy" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="sec-imputation-strategy"><span class="header-section-number">4.2</span> Imputation Strategy</h3>
<p>Based on the EDA, we implemented a two-tiered imputation strategy:</p>
<ul>
<li><strong>Categorical Encoding:</strong> For variables like <code>PoolQC</code>, <code>GarageType</code>, and <code>BsmtQual</code>, <code>NA</code> values were recoded to a explicit category (e.g., “No Pool”, “No Garage”) to preserve the information that the feature is missing. This was instructed in the problem statement, so this step was performed at the beginning, when reading the data. Note as well that variables such as <code>OverallQual</code> were converted into categorical, but this was not entirely required since it could have been used as a numerical predictor as well.</li>
<li><strong>Statistical Imputation:</strong> Remaining missing values in numerical columns were handled using statistical methods to ensure the model could utilize all available records. Specifically, they were imputed using the MICE algorithm (Multivariate Imputation by Chained-Equations) with Random Forest. To ensure robustness and prevent data leakage, the imputation model was trained exclusively on the training data while applying the learned patterns to complete the test set.</li>
</ul>
</section>
<section id="sec-feature-engineer" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="sec-feature-engineer"><span class="header-section-number">4.3</span> Feature Engineering</h3>
<p>To improve model interpretability and performance, we created several composite variables:</p>
<ul>
<li><strong><code>TotalSF</code> (Total Square Footage):</strong> We combined <code>TotalBsmtSF</code> and <code>GrLivArea</code> to create a single metric for the size of the house. This variable proved to have a higher correlation with price than its individual components.</li>
<li><strong><code>TotalBath</code>:</strong> We aggregated full and half baths (both above ground and basement) into a single count.</li>
<li><strong><code>HouseAge</code> &amp; <code>YearsSinceRemod</code>:</strong> We converted <code>YearBuilt</code> and <code>YearRemodAdd</code> into age variables relative to the year sold, which captures depreciation more effectively than raw years.</li>
<li><strong><code>TotalPorchSF</code>:</strong> Summed the area of all decks and porches.</li>
</ul>
</section>
<section id="variable-selection" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="variable-selection"><span class="header-section-number">4.4</span> Variable Selection</h3>
<p>To reduce noise and multicollinearity, we performed the following cleaning steps:</p>
<ul>
<li><strong>Near Zero Variance (NZV) Removal:</strong> Variables with almost no variation (e.g., <code>Utilities</code> where 99.9% were “AllPub”, <code>Street</code>, and <code>PoolArea</code>) were removed as they provide no predictive power.</li>
<li><strong>Redundancy Removal:</strong> Highly correlated features were removed. For instance, <code>GarageArea</code> was removed in favor of <code>GarageCars</code>, and <code>TotalBsmtSF</code> was removed as it is now included in <code>TotalSF</code>. <code>FullBath</code> in favor of <code>TotalBath</code>, etc.</li>
</ul>
<p>Note that for categorical variables a two-step feature selection was performed. First, we calculated a Cramer’s V matrix to detect multicollinearity. Second, we applied the Kruskal-Wallis test against (<span class="math inline">\(\log\)</span>-transformed) to evaluate feature importance, identifying and flagging variables that showed no statistically significant relationship (<span class="math inline">\(p &gt; 0.05\)</span>) with the target.</p>
<p>Following this approach we remained with 44 predictors, which is still quite a large number. Moreover, since categorical variables are turned into dummy variables when creating the model, this number could grow rapidly. For this reason, we used model selection techniques, as described in the following section.</p>
</section>
</section>
<section id="methodology-and-model-selection" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="methodology-and-model-selection"><span class="header-section-number">5</span> Methodology and Model Selection</h2>
<p>The model selection process evolved from simple linear regression toward advanced regularization and nonlinear modeling techniques. Our objective was not only to minimize error, but to capture the intrinsic complexity of the Ames housing market. We evaluated a full spectrum of algorithms, maintaining a rigorous comparison among them:</p>
<ol type="1">
<li><strong>Regularized Linear Models Ridge Lasso and Elastic Net:</strong> Implemented to manage high dimensionality and multicollinearity by penalizing coefficients in order to improve generalization.</li>
<li><strong>Principal Components Regression PCR:</strong> Used to reduce the dimensionality of the predictor space, at the cost of potential loss of interpretability.</li>
<li><strong>K Nearest Neighbors KNN:</strong> A nonparametric approach based on local similarity between properties.</li>
<li><strong>Stepwise Variable Selection Forward and Backward:</strong> Iterative methods based on information criteria AIC to identify the optimal subset of predictors.</li>
<li><strong>Generalized Additive Models GAM:</strong> Our final proposal, based on the use of smoothing splines to model nonlinear relationships.</li>
</ol>
<section id="evaluation-of-initial-candidates" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="evaluation-of-initial-candidates"><span class="header-section-number">5.1</span> Evaluation of Initial Candidates</h3>
<p>After extensive cross validation, a clear performance hierarchy emerged. <strong>Regularization models Lasso and Elastic Net</strong> established a very solid benchmark, outperforming <strong>stepwise selection methods</strong>, which tended toward mild overfitting due to greedy decisions on individual variables.</p>
<p>By contrast, <strong>PCR and KNN</strong> showed the weakest performance. PCR, by constructing components without considering the response variable, diluted critical nuances for appraisal, while KNN suffered from the curse of dimensionality, where distance in a space with more than 80 variables loses predictive meaning.</p>
</section>
<section id="the-winning-model" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="the-winning-model"><span class="header-section-number">5.2</span> The Winning Model</h3>
<p>Despite the robustness of linear models, we identified that the market does not behave in a purely additive and linear way. For this reason, we selected a <strong>Generalized Additive Model GAM</strong>, which was optimized through a process of statistical craftsmanship in three phases:</p>
<section id="nonlinearity-diagnosis-and-splines" class="level4" data-number="5.2.1">
<h4 data-number="5.2.1" class="anchored" data-anchor-id="nonlinearity-diagnosis-and-splines"><span class="header-section-number">5.2.1</span> Nonlinearity Diagnosis and Splines</h4>
<p>We conducted a linearity check by comparing linear fits against local smoothers LOESS. We confirmed that variables such as <code>TotalSF</code> and <code>HouseAge</code> exhibited curvature that a straight line could not capture.<br>
To optimize this, we implemented <strong>cubic regression splines <code>bs='cr'</code></strong>, manually tuning the basis dimension <strong>k</strong> up to <code>k=40</code>. This increase in flexibility allowed the model to learn complex patterns, such as diminishing returns to built area, without fitting noise.</p>
</section>
<section id="interactions" class="level4" data-number="5.2.2">
<h4 data-number="5.2.2" class="anchored" data-anchor-id="interactions"><span class="header-section-number">5.2.2</span> Interactions</h4>
<p>One of the most powerful findings in our optimization phase was that the effect of quantity square meters or bathrooms is modulated by quality. We did not include interactions at random. Instead, we used <strong>two way ANOVA</strong> to identify the most significant pairs:</p>
<ul>
<li><strong>Size Quality Interaction:</strong> We implemented a cross between <code>TotalSF</code> and <code>OverallQual</code>, capturing that an additional square meter in a luxury home is worth exponentially more than in a low quality home.</li>
<li><strong>Condition Dependent Depreciation:</strong> We introduced the term <code>s(HouseAge, by = OverallCond)</code>, allowing the aging curve of the property to differ according to its state of maintenance.</li>
</ul>
</section>
<section id="robustness-through-random-effects-and-reml" class="level4" data-number="5.2.3">
<h4 data-number="5.2.3" class="anchored" data-anchor-id="robustness-through-random-effects-and-reml"><span class="header-section-number">5.2.3</span> Robustness Through Random Effects and REML</h4>
<p>To avoid overfitting in variables with many categories, such as <code>Neighborhood</code>, we treated neighborhood as a <strong>random effect <code>bs='re'</code></strong>. This applies shrinkage that stabilizes predictions in areas with few observations.<br>
Finally, the model was fitted using <strong>Restricted Maximum Likelihood REML</strong>. Unlike other selection methods, REML provides a much more robust complexity penalty, ensuring that the model captures the true data structure rather than noise from the training set.</p>
</section>
</section>
<section id="benchmarking-conclusion" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="benchmarking-conclusion"><span class="header-section-number">5.3</span> Benchmarking Conclusion</h3>
<p>The final results table confirms our hypothesis. The <strong>GAM</strong> outperforms linear regularization models by being able to bend where market reality demands it. While Elastic Net and Lasso provide an excellent linear approximation, the optimized GAM with quality driven interactions and neighborhood random effects stands out as the most accurate and balanced predictive tool for this competition.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Model</th>
<th>RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>GAM (Splines)</td>
<td>0.1025</td>
</tr>
<tr class="even">
<td>2</td>
<td>ElasticNet</td>
<td>0.1089</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Lasso</td>
<td>0.1094</td>
</tr>
<tr class="even">
<td>4</td>
<td>Ridge</td>
<td>0.1120</td>
</tr>
<tr class="odd">
<td>5</td>
<td>LM Forward</td>
<td>0.1138</td>
</tr>
<tr class="even">
<td>6</td>
<td>LM Backward</td>
<td>0.1138</td>
</tr>
<tr class="odd">
<td>7</td>
<td>PCR</td>
<td>0.1247</td>
</tr>
<tr class="even">
<td>8</td>
<td>KNN</td>
<td>0.1738</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="results-discussion" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="results-discussion"><span class="header-section-number">6</span> Results &amp; Discussion</h2>
<section id="goodness-of-fit" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="goodness-of-fit"><span class="header-section-number">6.1</span> Goodness of Fit</h3>
<p>The <strong>Generalized Additive Model (GAM)</strong> with cubic splines proved to be a highly effective predictive tool, achieving a validation <strong>RMSE of 0.1025</strong>. Because the target variable is log-transformed, this value indicates that our model has an average prediction error of approximately <strong>10.25%</strong> in the original dollar price of the homes.</p>
<p>The model demonstrates an exceptional fit, explaining <strong>92% of the total deviance</strong> with an <strong>Adjusted R-squared of 0.914</strong>. To ensure the robustness of these results and guard against overfitting, we analyzed the following diagnostics from the model output:</p>
<ul>
<li><strong>Effective Degrees of Freedom (EDF):</strong> The smooth term for <strong>TotalSF</strong> has an EDF of <strong>4.22</strong>, and <strong>LotArea</strong> has an EDF of <strong>4.06</strong>, statistically confirming significant non-linear relationships that a standard linear model would fail to capture.</li>
<li><strong>Significance of Smooth Terms:</strong> Both <strong>TotalSF</strong> and <strong>LotArea</strong> are highly significant (<span class="math inline">\(p &lt; 2e-16\)</span>), justifying their inclusion as curved predictors rather than simple linear terms.</li>
<li><strong>Interaction Effects:</strong> The model successfully captured condition-dependent depreciation through the <code>s(HouseAge):OverallCond</code> interaction, which is highly significant for homes in average or good condition, specifically levels 5, 6, and 7 (<span class="math inline">\(p &lt; 2e-16\)</span>).</li>
</ul>
</section>
<section id="specific-questions-assessment" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="specific-questions-assessment"><span class="header-section-number">6.2</span> Specific Questions Assessment</h3>
<p><strong>Q1: What is the variable that contributes the most to explain the variability in price?</strong></p>
<p>Based on the GAM results, <strong>TotalSF (Total Square Footage)</strong> is the most critical predictor. It exhibits the highest F-statistic (<strong>74.88</strong>) among the smooth terms, indicating it has the strongest non-linear influence on the house price. This is followed closely by <strong>OverallQual</strong>, where moving from a quality level of 3 to 10 increases the log-price coefficient from <strong>0.29 to 0.71</strong>, representing a massive premium for high-end construction.</p>
<p><strong>Q2: What are the characteristics of the cheapest and most expensive houses?</strong></p>
<ul>
<li><strong>Most Expensive:</strong> These homes are primarily defined by an <strong>OverallQual of 9 or 10</strong>. They typically feature a large <strong>TotalSF</strong>, have at least <strong>3-car garages</strong> (Estimate: 0.037, <span class="math inline">\(p &lt; 6.41e-06\)</span>), and are located in premium neighborhoods like <strong>NridgHt</strong> or <strong>StoneBr</strong>. The model also shows they often have <strong>Excellent Kitchen Quality</strong> (Estimate: 0.095) and <strong>Finished Garages</strong> (Estimate: 0.102), both of which carry significant positive coefficients.</li>
<li><strong>Cheapest:</strong> Characterized by low <strong>OverallQual (1-4)</strong> and poor maintenance levels. These properties often have <strong>Fair or Typical basement quality</strong>, which carries a negative coefficient (e.g., BsmtQualFa: -0.113) relative to the baseline. They are frequently located in neighborhoods like <strong>IDOTRR</strong> or <strong>OldTown</strong>, where the renovation impact (<code>YearsSinceRemod</code>) is significantly lower or where specific local conditions depress the valuation.</li>
</ul>
</section>
</section>
<section id="conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">7</span> Conclusion</h2>
<p>By implementing a <strong>Generalized Additive Model (GAM)</strong>, we successfully captured the intrinsic non-linearities of the Ames housing market, such as the diminishing marginal returns of square footage and the complex interaction between a house’s age and its maintenance condition.</p>
<p>The model’s ability to explain <strong>92% of price deviance</strong> proves that while basic size metrics are the foundation of value, the “fine-tuning” provided by splines and random effects for neighborhoods is what drives high-precision forecasting. This approach allowed us to identify specific market drivers—like the significant impact of <strong>Fireplaces</strong> (<span class="math inline">\(p &lt; 9.84e-11\)</span>) and <strong>Garage Finishing</strong> (<span class="math inline">\(p &lt; 1.63e-05\)</span>)—that simpler linear models might overlook. Future iterations could explore tree-based models, such as <strong>XGBoost</strong>, to potentially capture higher-order interactions that linear or additive frameworks might still miss.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>